# Generated by Django 2.1.7 on 2019-02-26 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('specs', models.TextField()),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(default=0)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('components', models.ManyToManyField(related_name='components', to='shop.Component')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='usertype',
            field=models.CharField(choices=[('SELLER', 'Seller'), ('BUYER', 'Buyer'), ('ADMIN', 'Admin'), ('DEVICE_MANUFACTURER', 'Device_Manufacturer')], default='BUYER', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='sellers',
            field=models.ManyToManyField(related_name='sellers', to=settings.AUTH_USER_MODEL),
        ),
    ]
