# Generated by Django 2.1.7 on 2019-02-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.PositiveIntegerField()),
                ('pincode', models.PositiveIntegerField()),
                ('locality', models.TextField()),
                ('address', models.TextField()),
                ('city_district_town', models.CharField(choices=[('CITY', 'City'), ('DISTRICT', 'District'), ('TOWN', 'Town')], default='CITY', max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('landmark', models.CharField(max_length=50)),
                ('address_type', models.CharField(choices=[('HOME', 'Home'), ('WORK', 'Work')], default='HOME', max_length=50)),
            ],
        ),
    ]
