# Generated by Django 2.1.7 on 2019-03-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='model_number',
            field=models.CharField(max_length=50),
        ),
    ]
