# Generated by Django 2.1.7 on 2019-02-28 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
