# Generated by Django 2.1.7 on 2019-03-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190302_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
