# Generated by Django 2.1.7 on 2019-02-26 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_cart_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='model_numer',
            new_name='model_number',
        ),
    ]
