# Generated by Django 2.1.7 on 2019-03-02 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190302_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='sellers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='device',
            name='sellers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
