# Generated by Django 2.1.7 on 2019-02-26 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from shop.models import CustomUser
c = CustomUser.objects.get(id=1)

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190226_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='manufacturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='device_manufacturer', to=settings.AUTH_USER_MODEL),

            preserve_default=False,
        ),
    ]
