# Generated by Django 2.1.7 on 2019-02-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_customuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('SHIPPED', 'Shipped'), ('DISPATCHED', 'Dispatched'), ('APPROVED', 'Approved'), ('DELIVERED', 'Delivered')], max_length=50, null=True),
        ),
    ]
