# Generated by Django 2.1.7 on 2019-03-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_device_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='banners',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='banners',
        ),
        migrations.AddField(
            model_name='cart',
            name='devices',
            field=models.ManyToManyField(related_name='banner_cart', to='shop.Device'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='devices',
            field=models.ManyToManyField(to='shop.Device'),
        ),
    ]
