# Generated by Django 2.1.7 on 2019-02-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_data',
            field=models.DateTimeField(null=True),
        ),
    ]
