# Generated by Django 2.1.7 on 2019-02-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20190227_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='banner',
            field=models.ManyToManyField(related_name='banner_cart', to='shop.Banner'),
        ),
    ]
