# Generated by Django 2.1.7 on 2019-03-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20190302_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressone',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
    ]
