# Generated by Django 2.1.7 on 2019-03-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190302_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressone',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='addresstwo',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
