# Generated by Django 2.1.7 on 2019-02-27 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_cart_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='banner',
            new_name='banners',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
    ]
