# Generated by Django 2.1.7 on 2019-03-03 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20190303_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
