# Generated by Django 2.1.7 on 2019-03-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_device_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
