# Generated by Django 2.1.7 on 2019-02-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20190227_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
