# Generated by Django 2.1.7 on 2019-03-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_component_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='components',
            field=models.ManyToManyField(to='shop.Component'),
        ),
    ]
