# Generated by Django 2.1.7 on 2019-03-03 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_cart_components'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartToComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.Cart')),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.Component')),
            ],
        ),
        migrations.CreateModel(
            name='CartToDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.Cart')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.Device')),
            ],
        ),
    ]
