# Generated by Django 2.1.7 on 2019-03-03 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_carttocomponent_carttodevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='components',
            field=models.ManyToManyField(to='shop.Component'),
        ),
        migrations.AlterField(
            model_name='carttodevice',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Cart'),
        ),
        migrations.AlterField(
            model_name='carttodevice',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Device'),
        ),
    ]
