# Generated by Django 2.1.7 on 2019-03-03 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20190303_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='devices',
        ),
        migrations.AlterField(
            model_name='carttocomponent',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Cart'),
        ),
        migrations.AlterField(
            model_name='carttocomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Component'),
        ),
    ]
