# Generated by Django 2.1.7 on 2019-03-03 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_cart_devices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucket',
            name='files',
        ),
        migrations.AddField(
            model_name='file',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.Device'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Bucket',
        ),
    ]
