# Generated by Django 2.1.7 on 2019-03-03 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20190303_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='device',
        ),
    ]
