# Generated by Django 2.1.7 on 2019-03-03 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_device_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.File'),
        ),
    ]
